//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigDetail
    {
        public System.Guid ConfigID { get; set; }
        public string SMTPHost { get; set; }
        public int SMTPPort { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public System.Guid UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
