//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ConfigDetails = new HashSet<ConfigDetail>();
            this.EmailDetails = new HashSet<EmailDetail>();
        }
    
        public System.Guid UserID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Genre { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<ConfigDetail> ConfigDetails { get; set; }
        public virtual ICollection<EmailDetail> EmailDetails { get; set; }
    }
}
